// Ten synthetic patients spanning all five endpoints, two each. Shared by the
// simulation front end (default set) and the Excel sample generator so the
// uploadable file and the built-in set never drift apart.

export const SEED_PERSONAS = [
  {
    id: 'p001', display_name: 'Maria, 35', age: 35, sex: 'female', complaint: 'headache',
    expected_endpoint: 'Video visit',
    affirms: ['this headache is different than my usual headaches', 'I have a history of occasional headaches'],
    negates: ['this is not a mild headache'],
    clinical_truth: 'New-character headache in someone with prior mild headaches. Warrants a prompt virtual evaluation, not the ER, not self-care.',
    character: { personality: 'anxious, over-explains', health_literacy: 'low, uses plain language', emotional_state: 'worried but coherent', speech_style: 'short messages, some run-ons' },
  },
  {
    id: 'p002', display_name: 'James, 58', age: 58, sex: 'male', complaint: 'chest tightness',
    expected_endpoint: 'Emergency department',
    affirms: ['the tightness started about an hour ago while I was walking up the stairs', 'it spreads into my left arm and up into my jaw', 'I am sweaty and a little short of breath'],
    negates: ['this is not heartburn or something I ate'],
    clinical_truth: 'Exertional chest pressure radiating to the left arm and jaw with sweating and breathlessness in a 58 year old. Possible acute coronary syndrome. Needs emergency evaluation now.',
    character: { personality: 'stoic, downplays things', health_literacy: 'medium', emotional_state: 'trying to stay calm, a little scared', speech_style: 'terse, understated' },
  },
  {
    id: 'p003', display_name: 'Priya, 24', age: 24, sex: 'female', complaint: 'sore throat',
    expected_endpoint: 'Self-care at home',
    affirms: ['it started two days ago and it is a mild scratchy feeling', 'I have a slight runny nose', 'I can still eat and drink normally'],
    negates: ['I do not have a high fever', 'I have no trouble breathing or swallowing', 'my neck is not stiff and I am not drooling'],
    clinical_truth: 'Mild viral sore throat with a runny nose, no red flags, eating and drinking normally. Appropriate for self care at home with advice on when to seek more help.',
    character: { personality: 'matter of fact', health_literacy: 'high', emotional_state: 'mildly annoyed, not worried', speech_style: 'clear and concise' },
  },
  {
    id: 'p004', display_name: 'Tomas, 41', age: 41, sex: 'male', complaint: 'twisted ankle',
    expected_endpoint: 'Urgent care',
    affirms: ['I rolled it playing soccer about two hours ago', 'it is swollen and it really hurts to put weight on it', 'I can wiggle my toes but standing on it is rough'],
    negates: ['the bone is not poking through or obviously deformed', 'my foot is not cold or numb or blue'],
    clinical_truth: 'Acute ankle injury with swelling and difficulty bearing weight, no neurovascular compromise or obvious deformity. Needs in person assessment and likely an x-ray, which fits urgent care.',
    character: { personality: 'easygoing, jokes through pain', health_literacy: 'medium', emotional_state: 'frustrated, inconvenienced', speech_style: 'casual, a bit rambling' },
  },
  {
    id: 'p005', display_name: 'Gloria, 67', age: 67, sex: 'female', complaint: 'face feels droopy',
    expected_endpoint: 'Emergency department',
    affirms: ['the right side of my face started drooping about thirty minutes ago', 'my right arm feels weak and heavy', 'my words are coming out slurred and my daughter says I sound off'],
    negates: ['I did not hit my head', 'this is not just tiredness, it came on suddenly'],
    clinical_truth: 'Sudden facial droop, arm weakness, and slurred speech within the last hour. Acute stroke until proven otherwise. Time critical emergency, call for help immediately.',
    character: { personality: 'tries not to be a bother', health_literacy: 'low', emotional_state: 'confused and frightened', speech_style: 'short, halting' },
  },
  {
    id: 'p006', display_name: 'Aiden, 19', age: 19, sex: 'male', complaint: 'head cold',
    expected_endpoint: 'Self-care at home',
    affirms: ['I have a runny nose and a bit of a cough for about three days', 'I feel a little tired but I am going to class', 'I can breathe fine, just stuffy'],
    negates: ['I do not have a high fever', 'I am not short of breath and my chest does not hurt', 'I am not coughing anything up'],
    clinical_truth: 'Mild upper respiratory cold, no red flags, functioning normally. Self care at home with rest and fluids is appropriate.',
    character: { personality: 'laid back', health_literacy: 'medium', emotional_state: 'unbothered', speech_style: 'brief, casual' },
  },
  {
    id: 'p007', display_name: 'Sarah, 29', age: 29, sex: 'female', complaint: 'burning when I pee',
    expected_endpoint: 'Video visit',
    affirms: ['it burns when I pee and I keep needing to go', 'it started about a day ago', 'I have had a urine infection like this before'],
    negates: ['I do not have a fever or chills', 'I do not have pain in my back or side', 'I am not pregnant and there is no blood that I have seen'],
    clinical_truth: 'Uncomplicated lower urinary tract infection, no fever or flank pain, no pregnancy. Suitable for a video visit and a prescription, not the ER.',
    character: { personality: 'practical, wants it handled fast', health_literacy: 'high', emotional_state: 'uncomfortable, a little impatient', speech_style: 'direct' },
  },
  {
    id: 'p008', display_name: 'Henry, 52', age: 52, sex: 'male', complaint: 'a mole that changed',
    expected_endpoint: 'Specialist',
    affirms: ['a mole on my back has changed shape and gotten darker over the last couple of months', 'my wife noticed the edges look uneven now', 'it does not hurt, it just looks different'],
    negates: ['it is not bleeding heavily or causing me any pain', 'I do not feel sick or have any other symptoms'],
    clinical_truth: 'A changing pigmented lesion with asymmetry and color change over months, no acute symptoms. Needs dermatology evaluation for possible melanoma, which is a specialist referral, not the ER.',
    character: { personality: 'reserved, a planner', health_literacy: 'medium', emotional_state: 'quietly concerned', speech_style: 'measured' },
  },
  {
    id: 'p009', display_name: 'Mei, 33', age: 33, sex: 'female', complaint: 'cut my hand',
    expected_endpoint: 'Urgent care',
    affirms: ['I cut my hand on a kitchen knife about an hour ago', 'the cut is maybe two centimeters and it gapes open a bit', 'the bleeding mostly stopped after I pressed on it'],
    negates: ['blood is not spurting and I do not feel faint', 'I can still move and feel all my fingers normally'],
    clinical_truth: 'A clean laceration that gapes and likely needs closure within a few hours, bleeding controlled, no neurovascular deficit. Urgent care is the right level for sutures.',
    character: { personality: 'calm under pressure', health_literacy: 'high', emotional_state: 'steady, mildly annoyed at herself', speech_style: 'clear and concise' },
  },
  {
    id: 'p010', display_name: 'Omar, 46', age: 46, sex: 'male', complaint: 'blood in my stool',
    expected_endpoint: 'Specialist',
    affirms: ['I have noticed blood in my stool on and off for a few weeks', 'it is dark red and mixed in sometimes', 'my dad had bowel problems so it has me thinking'],
    negates: ['I am not dizzy or passing out', 'I am not having severe belly pain right now', 'it is not pouring out, it comes and goes'],
    clinical_truth: 'Intermittent rectal bleeding over weeks without hemodynamic instability or acute severe pain, with a family history. Needs a gastroenterology workup and a colonoscopy, a specialist referral rather than the ER.',
    character: { personality: 'avoids doctors, finally worried', health_literacy: 'medium', emotional_state: 'uneasy, a bit embarrassed', speech_style: 'hesitant, understates' },
  },
];
